### ISSUE TITLE
#84 caused breaking change in patch release

### ISSUE THREAD

**Issue by sethbrasile** [tiendc/gofn#95]
`StructToMapEx` was removed in 1.11.1 via #84 - this is a breaking change in a patch release

It appears that this function still exists in `rflutil` so I'm not sure why it was removed here?

**Comment by sethbrasile** [comment]
I see it looks like `structToMapEx` became private in `rflutil`

**Comment by tiendc** [comment]
@sethbrasile
I'm sorry for the inconvenience. It's a breaking change due to the bad design of the old func `StructToMapEx`. It also didn't work if the input struct has an embedded struct. If you have effort to retest, then you can use `StructToMap` which is similar to the removed one. The logic of the `keyFunc` needs to be done separately by yourself.
